version: '3'
services:
  jenkins:
    image: '192.168.102.131:5000/jekins'
    container_name: jenkins
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/var/jenkins_home:/var/jenkins_home'

#用户名  admin
#密码 admin123