server:
  port: 7880
spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          # 默认为false，设为true开启通过微服务创建路由的功能，即可以通过微服务名访问服务
          # http://localhost:8888/mall-order/order/findOrderByUserId/1
          enabled: true
      routes:
      - id: product-server1  #随便起名字   唯一即可
        uri: lb://product-server
        predicates:
        - Path=/product/**
      - id: order_server1
        uri: lb://order-server
        predicates:
        - Path=/order/**
      - id: auth_server
        uri: lb://auth-server
        predicates:
        - Path=/oauth/**,/user/**,/tiger/login,/login
      - id: portal-server
        uri: lb://portal-server
        predicates:
        - Path=/login/**
  main:
    allow-bean-definition-overriding: true

